### ISSUE TITLE
Expanded SWOT acronym on first use 

### ISSUE THREAD

**Issue by rjhintz** [rishidot/SWOT#2]
While SWOT is generally understood by the intended audience, it probably should be expanded on first use to save a click or two for those less familiar with the material. 

I'll propose some minimum language in a PR that you're welcome to expand, revise, or close/ignore.

**Comment by krishnan** [comment]
I agree. I am still figuring things out. I will try to add some instructions on PR so that there is some clarity. Any suggestions on this is welcome, especially the repositories are going to have documents and data
