### ISSUE TITLE
Contributing.md ?

### ISSUE THREAD

**Issue by rjhintz** [rishidot/SWOT#4]
Consider having a minimum `Contributing.md` so people know your expectations for PR workflow.

For example, do you accept PRs without a previous discussion in issues? Sometimes this can save a lot of time for someone developing a PR, revising the PR, revising the revision, *etc.*

Another example, probably less relevant, do you require `Signed-off-by: Super Developer <super.dev@gmail.com>`? See [What is the Sign Off feature in Git for?](http://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for) Probably not needed here, but take a look at the discussion. 

Disclosure: I don't use this myself since I'm the only one interested in my repos.  ;)

**Comment by krishnan** [comment]
Thanks. Yes, I am trying to put together a bare minimum contributing.md file and then iterate on it based on real world experience. I should have them ready soon

**Comment by krishnan** [comment]
Take a look when you have some time and let me know of your feedback

https://github.com/rishidot/SWOT/blob/master/Contributing.md

**Comment by rjhintz** [comment]
@krishnan 
A couple of immediate comments:

1. Move expansion of SWOT to first use in the text body
1.  In the first bullet:

> create an issue and use the commenting to disable the merits.

Should this be:

create an issue and use commenting to **discuss** the merits?

**Comment by rjhintz** [comment]
@krishnan 
Also, I have some other edit suggestions, generally minor, such as using Markdown formatting behavior to avoid long text source lines.

I've also included a proposed change to:

`we do not accept content inside paywall or a form`

to 

`we do not accept content inside a paywall of any form`

But maybe you mean registration required? 

I'll propose the PR and we can massage as you like.
